Repository bearcub971/Projet-GIT_2025, pull requests merged in 2025-01, with the labels that each got.

#1 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#2 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#3 Update .gitignore
  .gitignore
Labels: documentation

#5 Create pull_request_template.md
  pull_request_template.md
Labels: duplicate

#6 ajout de la gestion des recettes
  GestionDesRecettes.txt
Labels: good first issue

#8 Ajout des categorisations de recettes
  Categorisation_des_recettes.txt
Labels: good first issue

#9 notation
  notation.txt
Labels: invalid

#10 ajout des commenentaires pour les recettes
  CommentairesSurLesRecettes.txt
Labels: good first issue

#11 Sauvegarde des recettes favorites
  SauvegardeDesRecettesFavorites.txt
Labels: good first issue

#12 Import export
  ImportEx.txt
  notation.txt
Labels: documentation

#13 ajout des filtres
  FiltresIngrédients.txt
Labels: good first issue

#14 Responsivité_et_design_mobile
  Responsivité_et_design_mobile.txt
Labels: good first issue

#16 création page de connexion
  utilisateur.txt
Labels: good first issue, invalid

#17 fonctions sociales
  FonctionnalitésSociales.txt
Labels: bug, good first issue

#27 Recommandations personnalisées
  RecommandationsPersonnalisées.txt
Labels: good first issue

#32 valeur de nutrition
  nutrition.txt
Labels: good first issue

#35 version des recettes
  VersioningDesRecettes.txt
Labels: good first issue

#36 zone de test
  test.txt
  text.txt
Labels: good first issue

#37 Create pre-commit
  hooks/pre-commit
Labels: good first issue
